# Default values for blaster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

blaster:
  capabilityServiceApiUrl: "$(BLASTER_CAPABILITYSERVICE_API_URL)"
  awsJanitorApiUrl: "$(BLASTER_AWS_JANITOR_API_URL)"
  haraldApiUrl: "$(BLASTER_HARALD_API_URL)"

replicaCount: 1

global:
  labels:
    department: devex
    project: selfservice
image:
  repository: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/blaster
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "$(Build.BuildId)"

hotreload:
  enabled: false
  image:
    repository: ce/blaster-hotreload
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

priorityClass:
  enabled: true
  name: selfservice

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

# resources: {}
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
