name: $(Build.BuildId)
pool:
  vmImage: 'ubuntu-16.04'
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/auth-proxy/*
    - .vsts-ci-auth-proxy.yml
steps:

- bash: |
   sudo pip install setuptools
   sudo pip install awscli
   export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
   chmod +x ./pipeline-auth-proxy.sh
   ./pipeline-auth-proxy.sh $(Build.BuildId) $(System.DefaultWorkingDirectory)
  displayName: Pipeline Bash Script
