version: "3"

services:
  # Enables container to host communication:
  dockerhost:
    image: qoomon/docker-host
    cap_add:
      - 'NET_ADMIN'
      - 'NET_RAW'
    restart: on-failure
  # Simulates JWT header from AWS ALB:
  header-injector-proxy:
    build: 
      context: ./fake_dependencies/header-injector-proxy
    ports:
      - "5002:50802"
    depends_on:
      - auth-proxy
    environment:
      - FORWARD_ADDRESS=auth-proxy:50800
  # Transforms JWT from ALB to an vendor agnostic header:
  # Going forward it might enrich data about the user.
  auth-proxy:
    build: 
      context: ./src/auth-proxy
    ports:
      - "5003:50800"
    depends_on:
      - dockerhost
    environment:
      - FORWARD_ADDRESS=dockerhost:5000
  # Fake team service:
  teamservice:
    build: 
      context: ./fake_dependencies/teamservice
    ports:
      - "50900:3000"