apiVersion: v1
kind: Service
metadata:
  name: {{ include "blaster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
    app: {{ include "blaster.fullname" . }}
    component: blaster
    scrape-service-metrics: "true"
spec:
  ports:
    - name: metrics
      port: 80
      targetPort: web
    - name: echo
      port: 8080
      targetPort: echoweb
  selector:
    app: {{ include "blaster.fullname" . }}
