FROM node:14

WORKDIR app

COPY ./src/package.json ./
COPY ./src/webpack.config.js ./
COPY ./src/.babelrc ./
COPY ./src/Blaster.WebApi ./Blaster.WebApi

RUN npm install --no-progress && npm run-script build --no-progress
CMD npm start
